#include "OnlineModuleProvider.h"

// Generated by each library's codegen; the include directories come from the
// react_codegen_* targets that CMakeLists.txt links on the full flavor.
#include <RNCNetInfoSpec.h>
#include <RNRNWalletConnectModuleSpec.h>

namespace facebook::react {

std::shared_ptr<TurboModule> keycardpal_online_ModuleProvider(
    const std::string& moduleName,
    const JavaTurboModule::InitParams& params) {
  // Same shape as the autolinking_ModuleProvider that autolinking would have
  // generated for these two specs.
  if (auto module = RNRNWalletConnectModuleSpec_ModuleProvider(moduleName, params)) {
    return module;
  }
  if (auto module = RNCNetInfoSpec_ModuleProvider(moduleName, params)) {
    return module;
  }
  return nullptr;
}

} // namespace facebook::react
