repo_name: "Keycard Pal"
repo_description: "Official Keycard Pal release repository"
repo_url: "https://fdroid.keycardpal.com/repo"
repo_icon: icon.png
repo_keyalias: repokey

keystore: ./keystore.p12
keystorepass: {env: FDROID_KEYSTORE_PASS}
keypass: {env: FDROID_KEY_PASS}
keydname: "CN=keycardpal.com, O=Keycard Pal, C=RS"

archive_older: 3
allow_disabled_algorithms: false
